sudo: required
services:
  - docker

before_install: 
  - docker build -t jelenat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jelenat/react-test npm test -- --coverage

after_success:
  - docker build -t jelenat/multi-client ./client
  - docker build -t jelenat/multi-nginx ./nginx
  - docker build -t jelenat/multi-server ./server
  - docker build -t jelenat/multi-worker ./worker
